# Generated by Django 5.1.4 on 2024-12-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('day_birth', models.DateField()),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='buyerprod',
            name='id_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.shops'),
        ),
        migrations.AlterField(
            model_name='buyerprod',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categories'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categories'),
        ),
        migrations.AlterField(
            model_name='buyerprod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.user'),
        ),
    ]
