# Generated by Django 5.1.4 on 2024-12-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_user_alter_buyerprod_id_shop_alter_buyerprod_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.IntegerField(),
        ),
    ]
