# Generated by Django 5.1.4 on 2024-12-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_categories_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.CharField(max_length=255),
        ),
    ]
