# Generated by Django 5.1.4 on 2024-12-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('product', '0004_shops_is_active_alter_categories_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
